In [1]:
data="Twenty years ago, I dug a hole at a fever pitch while on a beach in South Padre Island, Texas. It was a shallow hole, but enough to contain vomit full of beer and Lunchables that I’d deposited into the trench. After wiping my mouth and scooping sand over the puke, I stood triumphant and raised a fist to a chorus of cheers. I’d just beer-bonged three Miller Lites on a challenge.For the uninitiated, beer bonging is when you pour beer into a funnel attached to a long piece of plastic tubing and then consume the alcohol as fast as possible. This process leaves you unbelievably drunk, but it’s a rite of passage among many college students. Granted, I couldn’t keep the liquid down, but the other college co-eds found the feat impressive.A few months earlier, I’d returned from the military’s Defense Language Institute, where I’d picked up another language. In search of a break from college and military routine, I joined my brother and a group of friends for Spring Break. My brother was the first to greet me post vomit escapade and slapped my increasingly pink shoulder, then handed me an ice-cold beer. I gratefully accepted and rinsed my mouth with the cold liquid."

In [2]:
data

'Twenty years ago, I dug a hole at a fever pitch while on a beach in South Padre Island, Texas. It was a shallow hole, but enough to contain vomit full of beer and Lunchables that I’d deposited into the trench. After wiping my mouth and scooping sand over the puke, I stood triumphant and raised a fist to a chorus of cheers. I’d just beer-bonged three Miller Lites on a challenge.For the uninitiated, beer bonging is when you pour beer into a funnel attached to a long piece of plastic tubing and then consume the alcohol as fast as possible. This process leaves you unbelievably drunk, but it’s a rite of passage among many college students. Granted, I couldn’t keep the liquid down, but the other college co-eds found the feat impressive.A few months earlier, I’d returned from the military’s Defense Language Institute, where I’d picked up another language. In search of a break from college and military routine, I joined my brother and a group of friends for Spring Break. My brother was the fi

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re

In [4]:
data = data.lower()
data

'twenty years ago, i dug a hole at a fever pitch while on a beach in south padre island, texas. it was a shallow hole, but enough to contain vomit full of beer and lunchables that i’d deposited into the trench. after wiping my mouth and scooping sand over the puke, i stood triumphant and raised a fist to a chorus of cheers. i’d just beer-bonged three miller lites on a challenge.for the uninitiated, beer bonging is when you pour beer into a funnel attached to a long piece of plastic tubing and then consume the alcohol as fast as possible. this process leaves you unbelievably drunk, but it’s a rite of passage among many college students. granted, i couldn’t keep the liquid down, but the other college co-eds found the feat impressive.a few months earlier, i’d returned from the military’s defense language institute, where i’d picked up another language. in search of a break from college and military routine, i joined my brother and a group of friends for spring break. my brother was the fi

In [5]:
data = re.sub('[^a-zA-z0-9\s]','',data)
data

'twenty years ago i dug a hole at a fever pitch while on a beach in south padre island texas it was a shallow hole but enough to contain vomit full of beer and lunchables that id deposited into the trench after wiping my mouth and scooping sand over the puke i stood triumphant and raised a fist to a chorus of cheers id just beerbonged three miller lites on a challengefor the uninitiated beer bonging is when you pour beer into a funnel attached to a long piece of plastic tubing and then consume the alcohol as fast as possible this process leaves you unbelievably drunk but its a rite of passage among many college students granted i couldnt keep the liquid down but the other college coeds found the feat impressivea few months earlier id returned from the militarys defense language institute where id picked up another language in search of a break from college and military routine i joined my brother and a group of friends for spring break my brother was the first to greet me post vomit es

In [6]:
!pip install tensorflow-cpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.8/231.8 MB 4.0 MB/s eta 0:00:00


In [7]:
!pip install keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
import tensorflow 
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D

In [9]:
max_fatures = 2000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(data)
X = tokenizer.texts_to_sequences(data)
X = pad_sequences(X)

In [10]:
embed_dim = 128
lstm_out = 196

model = Sequential()
model.add(Embedding(max_fatures, embed_dim,input_length = X.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(2,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1, 128)            256000    
                                                                 
 spatial_dropout1d (SpatialD  (None, 1, 128)           0         
 ropout1D)                                                       
                                                                 
 lstm (LSTM)                 (None, 196)               254800    
                                                                 
 dense (Dense)               (None, 2)                 394       
                                                                 
Total params: 511,194
Trainable params: 511,194
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
#vectorizing the tweet by the pre-fitted tokenizer instance
twt = tokenizer.texts_to_sequences(data)
#padding the tweet to have exactly the same shape as `embedding_2` input
twt = pad_sequences(twt, maxlen=28, dtype='int32', value=0)
print(twt)
sentiment = model.predict(twt,batch_size=1,verbose = 2)[0]
if(np.argmax(sentiment) == 0):
    print("negative")
elif (np.argmax(sentiment) == 1):
    print("positive")

[[ 0  0  0 ...  0  0  2]
 [ 0  0  0 ...  0  0 20]
 [ 0  0  0 ...  0  0  1]
 ...
 [ 0  0  0 ...  0  0 12]
 [ 0  0  0 ...  0  0  5]
 [ 0  0  0 ...  0  0  9]]
